
'''
389. Find the Difference

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

'''

# Initial solution - O(n) time, O(n) space
def findTheDifference(self, s, t):
    d = {}
    for char in t:
        if char in d:
            d[char] += 1
        else:
            d[char] = 1
    
    for char in s:
        if char in d:
            d[char] -= 1
            
    for key, value in d.items():
        if value > 0:
            return key


